## Step 1: Read raw PPP and location data from csv files

In [22]:
import pandas as pd

# Reading PPP Dataset
PPP_df = pd.read_csv('../data/interim/PPP_concatenated.csv')

In [23]:
PPP_df.head()

,Unnamed: 0,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,...,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate
0,0,9547507704,05/01/2020,464.0,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,NaN,29150-9662,...,Corporation,19248.0,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,NaN,773553.37,11/20/2020
1,1,9777677704,05/01/2020,464.0,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,NaN,29420-9000,...,Sole Proprietorship,19248.0,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,NaN,746336.24,08/12/2021
2,2,5791407702,05/01/2020,1013.0,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,NaN,98112-2922,...,Non-Profit Organization,9551.0,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,02/10/2021
3,3,6223567700,05/01/2020,920.0,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,NaN,92407-1740,...,Corporation,9551.0,"Bank of America, National Association",CHARLOTTE,NC,Male Owned,Non-Veteran,NaN,395264.11,09/10/2021
4,4,9662437702,05/01/2020,101.0,PPP,AERO BOX LLC,NaN,NaN,NaN,NaN,...,NaN,57328.0,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,370819.35,04/08/2021

In [24]:
# Reading Location Dataset
loc_df = pd.read_csv('../data/raw/loc_data/us_zip_fips_county.csv', encoding = "UTF-8")

In [25]:
loc_df.head()

,Zip Code,State Name,State Abrv,State Code,County Name,County Code,FIPS Code,ANSI Code,Centroid Lat,Centroid Long
0,501,New York,NY,36,Suffolk County,103,36103,974149,40.943554,-72.692218
1,544,New York,NY,36,Suffolk County,103,36103,974149,40.943554,-72.692218
2,6390,New York,NY,36,Suffolk County,103,36103,974149,40.943554,-72.692218
3,11701,New York,NY,36,Suffolk County,103,36103,974149,40.943554,-72.692218
4,11702,New York,NY,36,Suffolk County,103,36103,974149,40.943554,-72.692218

In [26]:
PPP_df.columns

Index(['Unnamed: 0', 'LoanNumber', 'DateApproved', 'SBAOfficeCode',
       'ProcessingMethod', 'BorrowerName', 'BorrowerAddress', 'BorrowerCity',
       'BorrowerState', 'BorrowerZip', 'LoanStatusDate', 'LoanStatus', 'Term',
       'SBAGuarantyPercentage', 'InitialApprovalAmount',
       'CurrentApprovalAmount', 'UndisbursedAmount', 'FranchiseName',
       'ServicingLenderLocationID', 'ServicingLenderName',
       'ServicingLenderAddress', 'ServicingLenderCity', 'ServicingLenderState',
       'ServicingLenderZip', 'RuralUrbanIndicator', 'HubzoneIndicator',
       'LMIIndicator', 'BusinessAgeDescription', 'ProjectCity',
       'ProjectCountyName', 'ProjectState', 'ProjectZip', 'CD', 'JobsReported',
       'NAICSCode', 'Race', 'Ethnicity', 'UTILITIES_PROCEED',
       'PAYROLL_PROCEED', 'MORTGAGE_INTEREST_PROCEED', 'RENT_PROCEED',
       'REFINANCE_EIDL_PROCEED', 'HEALTH_CARE_PROCEED',
       'DEBT_INTEREST_PROCEED', 'BusinessType', 'OriginatingLenderLocationID',
       'OriginatingLender', 'OriginatingLenderCity', 'OriginatingLenderState',
       'Gender', 'Veteran', 'NonProfit', 'ForgivenessAmount',
       'ForgivenessDate'],
      dtype='object')

## Step 2: Create 5 digit zip codes for both datasets

In [27]:
PPP_df["ZipCode"] = PPP_df['BorrowerZip'].str[:5]

In [28]:
loc_df["ZipCode"]=loc_df['Zip Code'].apply(lambda x: '{:05d}'.format(x))

In [40]:
PPP_df.dtypes

Unnamed: 0                       int64
LoanNumber                       int64
DateApproved                    object
SBAOfficeCode                  float64
ProcessingMethod                object
BorrowerName                    object
BorrowerAddress                 object
BorrowerCity                    object
BorrowerState                   object
BorrowerZip                     object
LoanStatusDate                  object
LoanStatus                      object
Term                             int64
SBAGuarantyPercentage            int64
InitialApprovalAmount          float64
CurrentApprovalAmount          float64
UndisbursedAmount              float64
FranchiseName                   object
ServicingLenderLocationID      float64
ServicingLenderName             object
ServicingLenderAddress          object
ServicingLenderCity             object
ServicingLenderState            object
ServicingLenderZip              object
RuralUrbanIndicator             object
HubzoneIndicator                object
LMIIndicator                    object
BusinessAgeDescription          object
ProjectCity                     object
ProjectCountyName               object
ProjectState                    object
ProjectZip                      object
CD                              object
JobsReported                   float64
NAICSCode                      float64
Race                            object
Ethnicity                       object
UTILITIES_PROCEED              float64
PAYROLL_PROCEED                float64
MORTGAGE_INTEREST_PROCEED      float64
RENT_PROCEED                   float64
REFINANCE_EIDL_PROCEED         float64
HEALTH_CARE_PROCEED            float64
DEBT_INTEREST_PROCEED          float64
BusinessType                    object
OriginatingLenderLocationID    float64
OriginatingLender               object
OriginatingLenderCity           object
OriginatingLenderState          object
Gender                          object
Veteran                         object
NonProfit                       object
ForgivenessAmount              float64
ForgivenessDate                 object
ZipCode                         object
dtype: object

In [41]:
loc_df.dtypes

Zip Code           int64
State Name        object
State Abrv        object
State Code         int64
County Name       object
County Code        int64
FIPS Code          int64
ANSI Code          int64
Centroid Lat     float64
Centroid Long    float64
ZipCode           object
dtype: object

In [29]:
PPP_df.head()

,Unnamed: 0,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,...,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate,ZipCode
0,0,9547507704,05/01/2020,464.0,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,NaN,29150-9662,...,19248.0,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,NaN,773553.37,11/20/2020,29150
1,1,9777677704,05/01/2020,464.0,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,NaN,29420-9000,...,19248.0,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,NaN,746336.24,08/12/2021,29420
2,2,5791407702,05/01/2020,1013.0,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,NaN,98112-2922,...,9551.0,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,02/10/2021,98112
3,3,6223567700,05/01/2020,920.0,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,NaN,92407-1740,...,9551.0,"Bank of America, National Association",CHARLOTTE,NC,Male Owned,Non-Veteran,NaN,395264.11,09/10/2021,92407
4,4,9662437702,05/01/2020,101.0,PPP,AERO BOX LLC,NaN,NaN,NaN,NaN,...,57328.0,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,370819.35,04/08/2021,NaN

In [32]:
list(PPP_df.ZipCode.unique())

['29150',
 '29420',
 '98112',
 '92407',
 nan,
 '32259',
 '99503',
 '99723',
 '99502',
 '99518',
 '99603',
 '99501',
 '99645',
 '99515',
 '99654',
 '99709',
 '99701',
 '99835',
 '99587',
 '99508',
 '99762',
 '99801',
 '99516',
 '99520',
 '99901',
 '99707',
 '99693',
 '99507',
 '99573',
 '99833',
 '99615',
 '99705',
 '99669',
 '99517',
 '99840',
 '99509',
 '99574',
 '99611',
 '99510',
 '99664',
 '99686',
 '99711',
 '99706',
 '99504',
 '99519',
 '99623',
 '99631',
 '99577',
 '99588',
 '99737',
 '99752',
 '99676',
 '99687',
 '99921',
 '99652',
 '99803',
 '99613',
 '99559',
 '99567',
 '99576',
 '99672',
 '99689',
 '99925',
 '99712',
 '99820',
 '99556',
 '99780',
 '99692',
 '99633',
 '99755',
 '99511',
 '99708',
 '99827',
 '99929',
 '99624',
 '99572',
 '99775',
 '99825',
 '99558',
 '99653',
 '99688',
 '99682',
 '99586',
 '99514',
 '99674',
 '99832',
 '99606',
 '99523',
 '99830',
 '99743',
 '99566',
 '99655',
 '99524',
 '99610',
 '99710',
 '99824',
 '99540',
 '99563',
 '99926',
 '99635',
 '99661',
 '99695',
 '99760',
 '35203',
 '35216',
 '35242',
 '36303',
 '35768',
 '35243',
 '35601',
 '35806',
 '36602',
 '35582',
 '35661',
 '36330',
 '35209',
 '35080',
 '35205',
 '35654',
 '36615',
 '36260',
 '35223',
 '35022',
 '35801',
 '35630',
 '35640',
 '35055',
 '35476',
 '35217',
 '35805',
 '36446',
 '35976',
 '36117',
 '35490',
 '36617',
 '35020',
 '35210',
 '36102',
 '35611',
 '36580',
 '35802',
 '35179',
 '35244',
 '35401',
 '36582',
 '36116',
 '35234',
 '36092',
 '36049',
 '35254',
 '35741',
 '36104',
 '36305',
 '35214',
 '36732',
 '35150',
 '36693',
 '36606',
 '35222',
 '36551',
 '36542',
 '36079',
 '36604',
 '36535',
 '36608',
 '35211',
 '36702',
 '36109',
 '36695',
 '35501',
 '35124',
 '35502',
 '36867',
 '36066',
 '35173',
 '36603',
 '35060',
 '35962',
 '36618',
 '36830',
 '35807',
 '35442',
 '35042',
 '36203',
 '35212',
 '35219',
 '35950',
 '35121',
 '35904',
 '36360',
 '35201',
 '35040',
 '35570',
 '35673',
 '36426',
 '36801',
 '36853',
 '35096',
 '36081',
 '35146',
 '35404',
 '35811',
 '35824',
 '35188',
 '35816',
 '36619',
 '36302',
 '36616',
 '35228',
 '35405',
 '36312',
 '35064',
 '35023',
 '36264',
 '35137',
 '36613',
 '35160',
 '35235',
 '36037',
 '36340',
 '36106',
 '35226',
 '35967',
 '35011',
 '36105',
 '35406',
 '36251',
 '35758',
 '36268',
 '35007',
 '35563',
 '36460',
 '36832',
 '35594',
 '36701',
 '36301',
 '36605',
 '35653',
 '35901',
 '36527',
 '36532',
 '35957',
 '35161',
 '36108',
 '36607',
 '35906',
 '36561',
 '35580',
 '35010',
 '36351',
 '35213',
 '36854',
 '36250',
 '36323',
 '36401',
 '36207',
 '35622',
 '36502',
 '36078',
 '35553',
 '36804',
 '36445',
 '35077',
 '35803',
 '35671',
 '36748',
 '35125',
 '36507',
 '36121',
 '36110',
 '35960',
 '36107',
 '36467',
 '35954',
 '36521',
 '36027',
 '36609',
 '36421',
 '35004',
 '35660',
 '36010',
 '35961',
 '35968',
 '35971',
 '35619',
 '35238',
 '35057',
 '36612',
 '36124',
 '36304',
 '35951',
 '35151',
 '35403',
 '35215',
 '35473',
 '35761',
 '36863',
 '35045',
 '36361',
 '36852',
 '35674',
 '35652',
 '35907',
 '36610',
 '35470',
 '35576',
 '36505',
 '36660',
 '35978',
 '36572',
 '36871',
 '36862',
 '36526',
 '36544',
 '36541',
 '35043',
 '35634',
 '35575',
 '36089',
 '36201',
 '35058',
 '35810',
 '35603',
 '35756',
 '35068',
 '35602',
 '36310',
 '36111',
 '36068',
 '35207',
 '35204',
 '36265',
 '36545',
 '35504',
 '36451',
 '35033',
 '35094',
 '35118',
 '35233',
 '35116',
 '35808',
 '36523',
 '35111',
 '35550',
 '36874',
 '36761',
 '36824',
 '35974',
 '36831',
 '36321',
 '35769',
 '35180',
 '35474',
 '35444',
 '36518',
 '36744',
 '36528',
 '36611',
 '35218',
 '36054',
 '36043',
 '36525',
 '35804',
 '35613',
 '36420',
 '35592',
 '36756',
 '35143',
 '35046',
 '35128',
 '35402',
 '36870',
 '35456',
 '35643',
 '36575',
 '35763',
 '35206',
 '35453',
 '36274',
 '35016',
 '36533',
 '35462',
 '36522',
 '36032',
 '36509',
 '35034',
 '35565',
 '35224',
 '35772',
 '36703',
 '36075',
 '36904',
 '36784',
 '35618',
 '35555',
 '36272',
 '35471',
 '35071',
 '35175',
 '35035',
 '35171',
 '36206',
 '36691',
 '35739',
 '35503',
 '35903',
 '35148',
 '35119',
 '35147',
 '36025',
 '36511',
 '36453',
 '36921',
 '36123',
 '35905',
 '35443',
 '36877',
 '35178',
 '35072',
 '35750',
 '36530',
 '36350',
 '36869',
 '36202',
 '35073',
 '36279',
 '36587',
 '36919',
 '36441',
 '36722',
 '36345',
 '36866',
 '36726',
 '36567',
 '36093',
 '36024',
 '35126',
 '35543',
 '35645',
 '36750',
 '35044',
 '36067',
 '36278',
 '35633',
 '35255',
 '36571',
 '35953',
 '36009',
 '35759',
 '36803',
 '35221',
 '35115',
 '35032',
 '36578',
 '35981',
 '35172',
 '36574',
 '35091',
 '35478',
 '35062',
 '35056',
 '35579',
 '36205',
 '36471',
 '35051',
 '35202',
 '36856',
 '35984',
 '36204',
 '36555',
 '35581',
 '35548',
 '35019',
 '36271',
 '36041',
 '35236',
 '36925',
 '36035',
 '35481',
 '35120',
 '35752',
 '36320',
 '35208',
 '36057',
 '36276',
 '36633',
 '35083',
 '35031',
 '35764',
 '35986',
 '36477',
 '36547',
 '35987',
 '36311',
 '36371',
 '35748',
 '35085',
 '35053',
 '35754',
 '35142',
 '35549',
 '36553',
 '36513',
 '36442',
 '35546',
 '35773',
 '35540',
 '35757',
 '35650',
 '35952',
 '35662',
 '35980',
 '36549',
 '36868',
 '35087',
 '36375',
 '36850',
 '35475',
 '35407',
 '36064',
 '36040',
 '36577',
 '35186',
 '35005',
 '35989',
 '35061',
 '35672',
 '36663',
 '35956',
 '35966',
 '36013',
 '35079',
 '35760',
 '35078',
 '35133',
 '36083',
 '36022',
 '35572',
 '36069',
 '36352',
 '35670',
 '36051',
 '36065',
 '35184',
 '36344',
 '35117',
 '35149',
 '35253',
 '36855',
 '36266',
 '36456',
 '36768',
 '36858',
 '36671',
 '36046',
 '36470',
 '35452',
 '36773',
 '35959',
 '36875',
 '36769',
 '35616',
 '35014',
 '36689',
 '35131',
 '36322',
 '36006',
 '36759',
 '35646',
 '36427',
 '35988',
 '36016',
 '36590',
 '35089',
 '36785',
 '36786',
 '30269',
 '35469',
 '36560',
 '35586',
 '35585',
 '36782',
 '35578',
 '36675',
 '35747',
 '36807',
 '35612',
 '35983',
 '36536',
 '35677',
 '36277',
 '35063',
 '36273',
 '98506',
 '36581',
 '35812',
 '36749',
 '35564',
 '36373',
 '35631',
 '36476',
 '35958',
 '35006',
 '35466',
 '36436',
 '36849',
 '36512',
 '35049',
 '35614',
 '35545',
 '33758',
 '36576',
 '36034',
 '36319',
 '35649',
 '35114',
 '35744',
 '36916',
 '36539',
 '36861',
 '35755',
 '36685',
 '35620',
 '36559',
 '36318',
 '35647',
 '36793',
 '35610',
 '36579',
 '36585',
 '36752',
 '35902',
 '36047',
 '35621',
 '72764',
 '71730',
 '72205',
 '72703',
 '71655',
 '72736',
 '72209',
 '72745',
 '72801',
 '72034',
 '72223',
 '72202',
 '72116',
 '72143',
 '72501',
 '72032',
 '72704',
 '72701',
 '72204',
 '72203',
 '72702',
 '72543',
 '71998',
 '72104',
 '72712',
 '72601',
 '71901',
 '72903',
 '72901',
 '72076',
 '72908',
 '71701',
 '71913',
 '72765',
 '72830',
 '72201',
 '71635',
 '72118',
 '72018',
 '71909',
 '72360',
 '72206',
 '72756',
 '72315',
 '72562',
 '72031',
 '72022',
 '72770',
 '72211',
 '72472',
 '71841',
 '72766',
 '72212',
 '71953',
 '72956',
 '72404',
 '72916',
 '72401',
 '72117',
 '72110',
 '72653',
 '72762',
 '71753',
 '72727',
 '72044',
 '72454',
 '71857',
 '72902',
 '71852',
 '72120',
 '71671',
 '72342',
 '71968',
 '72455',
 '72114',
 '72042',
 '72650',
 '71957',
 '72833',
 '72301',
 '71653',
 '72023',
 '71854',
 '72679',
 '72923',
 '72758',
 '72450',
 '72422',
 '71801',
 '72616',
 '72021',
 '71638',
 '72476',
 '71602',
 '71603',
 '71923',
 '72802',
 '72396',
 '72210',
 '71667',
 '72904',
 '72634',
 '72602',
 '71914',
 '72432',
 '72761',
 '71639',
 '72113',
 '72103',
 '72019',
 '72231',
 '72936',
 '72160',
 '71822',
 '72740',
 '72913',
 '72855',
 '72635',
 '72395',
 '72303',
 '72503',
 '72921',
 '72227',
 '72012',
 '72853',
 '72015',
 '71845',
 '72086',
 '72951',
 '72390',
 '72405',
 '72739',
 '72082',
 '71654',
 '71742',
 '72045',
 '72207',
 '72217',
 '71675',
 '72834',
 '72011',
 '72927',
 '72002',
 '71744',
 '71903',
 '72335',
 '72039',
 '72150',
 '72632',
 '72576',
 '72718',
 '72451',
 '71646',
 '72845',
 '72811',
 '71945',
 '72058',
 '71601',
 '72651',
 '72403',
 '72638',
 '72732',
 '72364',
 '72106',
 '72370',
 '72626',
 '72556',
 '72081',
 '72129',
 '71839',
 '72949',
 '72112',
 '71611',
 '72753',
 '72366',
 '71943',
 '72131',
 '72734',
 '72415',
 '72933',
 '71973',
 '72744',
 '71766',
 '72084',
 '71964',
 '72730',
 '72219',
 '72937',
 '72006',
 '72560',
 '72024',
 '72958',
 '72521',
 '72738',
 '72641',
 '72214',
 '71956',
 '72713',
 '71763',
 '72417',
 '72438',
 '71832',
 '72687',
 '71749',
 '72402',
 '72540',
 '72088',
 '72137',
 '72173',
 '72645',
 '72055',
 '71640',
 '71860',
 '72947',
 '72447',
 '72327',
 '72519',
 '72918',
 '72943',
 '72046',
 '71665',
 '72416',
 '72823',
 '72749',
 '72437',
 '72170',
 '72629',
 '72029',
 '72821',
 '72865',
 '72089',
 '72316',
 '72715',
 '71765',
 '72642',
 '72145',
 '72433',
 '71754',
 '72101',
 '72421',
 '71647',
 '72216',
 '72442',
 '72376',
 '72119',
 '71642',
 '71922',
 '72326',
 '72324',
 '71861',
 '72064',
 '72906',
 '72534',
 '71724',
 '72479',
 '72719',
 '71762',
 '72142',
 '72858',
 '72670',
 '72365',
 '72135',
 '72662',
 '72033',
 '72536',
 '72087',
 '72461',
 '71942',
 '72644',
 '71764',
 '71921',
 '71960',
 '71958',
 '72111',
 '72020',
 '72132',
 '72065',
 '72003',
 '72941',
 '71658',
 '72542',
 '72513',
 '72457',
 '72067',
 '72222',
 '71836',
 '72336',
 '72714',
 '72122',
 '72127',
 '72524',
 '72016',
 '72843',
 '71846',
 '71612',
 '72392',
 '72126',
 '72311',
 '72152',
 '71842',
 '72757',
 '72532',
 '72083',
 '71838',
 '72004',
 '72654',
 '72512',
 '72373',
 '72221',
 '72932',
 '72944',
 '72840',
 '72658',
 '72948',
 '72619',
 '71662',
 '72837',
 '71670',
 '72952',
 '71745',
 '72443',
 '72013',
 '71743',
 '72841',
 '72414',
 '72176',
 '71840',
 '72682',
 '72435',
 '72260',
 '71759',
 '71826',
 '72857',
 '72675',
 '72041',
 '72935',
 '71711',
 '72631',
 '72722',
 '72860',
 '72926',
 '72774',
 '72611',
 '71770',
 '72010',
 '96799',
 '85260',
 '86504',
 '85018',
 '85711',
 '85250',
 '85012',
 '85054',
 '85016',
 '85027',
 '85255',
 '85251',
 '85202',
 '85254',
 '85281',
 '85297',
 '85006',
 '85029',
 '85004',
 '85008',
 '85032',
 ...]

In [33]:
loc_df.head()

,Zip Code,State Name,State Abrv,State Code,County Name,County Code,FIPS Code,ANSI Code,Centroid Lat,Centroid Long,ZipCode
0,501,New York,NY,36,Suffolk County,103,36103,974149,40.943554,-72.692218,00501
1,544,New York,NY,36,Suffolk County,103,36103,974149,40.943554,-72.692218,00544
2,6390,New York,NY,36,Suffolk County,103,36103,974149,40.943554,-72.692218,06390
3,11701,New York,NY,36,Suffolk County,103,36103,974149,40.943554,-72.692218,11701
4,11702,New York,NY,36,Suffolk County,103,36103,974149,40.943554,-72.692218,11702

## Step 3: Merge location data to the PPP dataset

In [45]:
pd.set_option('display.max_columns', None)
merged_df = PPP_df.merge(loc_df, how='left', on='ZipCode')
merged_df.head()

,Unnamed: 0,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,LoanStatus,Term,SBAGuarantyPercentage,InitialApprovalAmount,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,ServicingLenderAddress,ServicingLenderCity,ServicingLenderState,ServicingLenderZip,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,BusinessAgeDescription,ProjectCity,ProjectCountyName,ProjectState,ProjectZip,CD,JobsReported,NAICSCode,Race,Ethnicity,UTILITIES_PROCEED,PAYROLL_PROCEED,MORTGAGE_INTEREST_PROCEED,RENT_PROCEED,REFINANCE_EIDL_PROCEED,HEALTH_CARE_PROCEED,DEBT_INTEREST_PROCEED,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate,ZipCode,Zip Code,State Name,State Abrv,State Code,County Name,County Code,FIPS Code,ANSI Code,Centroid Lat,Centroid Long
0,0,9547507704,05/01/2020,464.0,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,NaN,29150-9662,12/18/2020,Paid in Full,24,100,769358.78,769358.78,0.0,NaN,19248.0,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,N,N,Existing or more than 2 years old,Sumter,SUMTER,SC,29150-9662,SC-05,62.0,325510.0,Unanswered,Unknown/NotStated,NaN,769358.78,NaN,NaN,NaN,NaN,NaN,Corporation,19248.0,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,NaN,773553.37,11/20/2020,29150,29150.0,South Carolina,SC,45.0,Sumter County,85.0,45085.0,1244717.0,33.916253,-80.382288
1,1,9777677704,05/01/2020,464.0,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,NaN,29420-9000,09/28/2021,Paid in Full,24,100,736927.79,736927.79,0.0,NaN,19248.0,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,Y,Y,Existing or more than 2 years old,North Charleston,CHARLESTON,SC,29420-9000,SC-06,73.0,561730.0,White,Unknown/NotStated,NaN,736927.79,NaN,NaN,NaN,NaN,NaN,Sole Proprietorship,19248.0,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,NaN,746336.24,08/12/2021,29420,29420.0,South Carolina,SC,45.0,Dorchester County,35.0,45035.0,1247998.0,33.082186,-80.404697
2,2,5791407702,05/01/2020,1013.0,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,NaN,98112-2922,03/17/2021,Paid in Full,24,100,691355.00,691355.00,0.0,NaN,9551.0,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SEATTLE,KING,WA,98112-2922,WA-07,75.0,NaN,Unanswered,Unknown/NotStated,NaN,691355.00,NaN,NaN,NaN,NaN,NaN,Non-Profit Organization,9551.0,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,02/10/2021,98112,98112.0,Washington,WA,53.0,King County,33.0,53033.0,1531933.0,47.490599,-121.833996
3,3,6223567700,05/01/2020,920.0,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,NaN,92407-1740,10/16/2021,Paid in Full,24,100,499871.00,499871.00,0.0,NaN,9551.0,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SAN BERNARDINO,SAN BERNARDINO,CA,92407-1740,CA-23,21.0,236115.0,American Indian or Alaska Native,Not Hispanic or Latino,NaN,499871.00,NaN,NaN,NaN,NaN,NaN,Corporation,9551.0,"Bank of America, National Association",CHARLOTTE,NC,Male Owned,Non-Veteran,NaN,395264.11,09/10/2021,92407,92407.0,California,CA,6.0,San Bernardino County,71.0,6071.0,277300.0,34.857220,-116.181197
4,4,9662437702,05/01/2020,101.0,PPP,AERO BOX LLC,NaN,NaN,NaN,NaN,08/17/2021,Paid in Full,24,100,367437.00,367437.00,0.0,NaN,57328.0,The Huntington National Bank,17 S High St.,COLUMBUS,OH,43215-3413,U,N,N,Unanswered,NaN,NaN,NaN,NaN,NaN,25.0,484210.0,Unanswered,Unknown/NotStated,NaN,367437.00,NaN,NaN,NaN,NaN,NaN,NaN,57328.0,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,370819.35,04/08/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
merged_df.columns

Index(['Unnamed: 0', 'LoanNumber', 'DateApproved', 'SBAOfficeCode',
       'ProcessingMethod', 'BorrowerName', 'BorrowerAddress', 'BorrowerCity',
       'BorrowerState', 'BorrowerZip', 'LoanStatusDate', 'LoanStatus', 'Term',
       'SBAGuarantyPercentage', 'InitialApprovalAmount',
       'CurrentApprovalAmount', 'UndisbursedAmount', 'FranchiseName',
       'ServicingLenderLocationID', 'ServicingLenderName',
       'ServicingLenderAddress', 'ServicingLenderCity', 'ServicingLenderState',
       'ServicingLenderZip', 'RuralUrbanIndicator', 'HubzoneIndicator',
       'LMIIndicator', 'BusinessAgeDescription', 'ProjectCity',
       'ProjectCountyName', 'ProjectState', 'ProjectZip', 'CD', 'JobsReported',
       'NAICSCode', 'Race', 'Ethnicity', 'UTILITIES_PROCEED',
       'PAYROLL_PROCEED', 'MORTGAGE_INTEREST_PROCEED', 'RENT_PROCEED',
       'REFINANCE_EIDL_PROCEED', 'HEALTH_CARE_PROCEED',
       'DEBT_INTEREST_PROCEED', 'BusinessType', 'OriginatingLenderLocationID',
       'OriginatingLender', 'OriginatingLenderCity', 'OriginatingLenderState',
       'Gender', 'Veteran', 'NonProfit', 'ForgivenessAmount',
       'ForgivenessDate', 'ZipCode', 'Zip Code', 'State Name', 'State Abrv',
       'State Code', 'County Name', 'County Code', 'FIPS Code', 'ANSI Code',
       'Centroid Lat', 'Centroid Long'],
      dtype='object')

In [37]:
joined_df = PPP_df.join(loc_df, on='ZipCode', how='left', lsuffix='_t1', rsuffix='_t1')
joined_df.head()

ValueError: You are trying to merge on object and int64 columns. If you wish to proceed you should use pd.concat