# 1.0 Data preparation

In [1]:
import numpy as np
import pandas as pd
import math
import base64

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
# Read the data file and take a look at the data
df = pd.read_csv('../data/interim/PPP_concatenated.csv')
df.head()

,Unnamed: 0,LoanNumber,DateApproved,SBAOfficeCode,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerCity,BorrowerState,BorrowerZip,LoanStatusDate,LoanStatus,Term,SBAGuarantyPercentage,InitialApprovalAmount,CurrentApprovalAmount,UndisbursedAmount,FranchiseName,ServicingLenderLocationID,ServicingLenderName,ServicingLenderAddress,ServicingLenderCity,ServicingLenderState,ServicingLenderZip,RuralUrbanIndicator,HubzoneIndicator,LMIIndicator,BusinessAgeDescription,ProjectCity,ProjectCountyName,ProjectState,ProjectZip,CD,JobsReported,NAICSCode,Race,Ethnicity,UTILITIES_PROCEED,PAYROLL_PROCEED,MORTGAGE_INTEREST_PROCEED,RENT_PROCEED,REFINANCE_EIDL_PROCEED,HEALTH_CARE_PROCEED,DEBT_INTEREST_PROCEED,BusinessType,OriginatingLenderLocationID,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,NonProfit,ForgivenessAmount,ForgivenessDate
0,0,9547507704,05/01/2020,464.0,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,NaN,29150-9662,12/18/2020,Paid in Full,24,100,769358.78,769358.78,0.0,NaN,19248.0,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,N,N,Existing or more than 2 years old,Sumter,SUMTER,SC,29150-9662,SC-05,62.0,325510.0,Unanswered,Unknown/NotStated,NaN,769358.78,NaN,NaN,NaN,NaN,NaN,Corporation,19248.0,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,NaN,773553.37,11/20/2020
1,1,9777677704,05/01/2020,464.0,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,NaN,29420-9000,09/28/2021,Paid in Full,24,100,736927.79,736927.79,0.0,NaN,19248.0,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,Y,Y,Existing or more than 2 years old,North Charleston,CHARLESTON,SC,29420-9000,SC-06,73.0,561730.0,White,Unknown/NotStated,NaN,736927.79,NaN,NaN,NaN,NaN,NaN,Sole Proprietorship,19248.0,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,NaN,746336.24,08/12/2021
2,2,5791407702,05/01/2020,1013.0,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,NaN,98112-2922,03/17/2021,Paid in Full,24,100,691355.00,691355.00,0.0,NaN,9551.0,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SEATTLE,KING,WA,98112-2922,WA-07,75.0,NaN,Unanswered,Unknown/NotStated,NaN,691355.00,NaN,NaN,NaN,NaN,NaN,Non-Profit Organization,9551.0,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,02/10/2021
3,3,6223567700,05/01/2020,920.0,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,NaN,92407-1740,10/16/2021,Paid in Full,24,100,499871.00,499871.00,0.0,NaN,9551.0,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SAN BERNARDINO,SAN BERNARDINO,CA,92407-1740,CA-23,21.0,236115.0,American Indian or Alaska Native,Not Hispanic or Latino,NaN,499871.00,NaN,NaN,NaN,NaN,NaN,Corporation,9551.0,"Bank of America, National Association",CHARLOTTE,NC,Male Owned,Non-Veteran,NaN,395264.11,09/10/2021
4,4,9662437702,05/01/2020,101.0,PPP,AERO BOX LLC,NaN,NaN,NaN,NaN,08/17/2021,Paid in Full,24,100,367437.00,367437.00,0.0,NaN,57328.0,The Huntington National Bank,17 S High St.,COLUMBUS,OH,43215-3413,U,N,N,Unanswered,NaN,NaN,NaN,NaN,NaN,25.0,484210.0,Unanswered,Unknown/NotStated,NaN,367437.00,NaN,NaN,NaN,NaN,NaN,NaN,57328.0,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,370819.35,04/08/2021

In [4]:
df.columns

Index(['Unnamed: 0', 'LoanNumber', 'DateApproved', 'SBAOfficeCode',
       'ProcessingMethod', 'BorrowerName', 'BorrowerAddress', 'BorrowerCity',
       'BorrowerState', 'BorrowerZip', 'LoanStatusDate', 'LoanStatus', 'Term',
       'SBAGuarantyPercentage', 'InitialApprovalAmount',
       'CurrentApprovalAmount', 'UndisbursedAmount', 'FranchiseName',
       'ServicingLenderLocationID', 'ServicingLenderName',
       'ServicingLenderAddress', 'ServicingLenderCity', 'ServicingLenderState',
       'ServicingLenderZip', 'RuralUrbanIndicator', 'HubzoneIndicator',
       'LMIIndicator', 'BusinessAgeDescription', 'ProjectCity',
       'ProjectCountyName', 'ProjectState', 'ProjectZip', 'CD', 'JobsReported',
       'NAICSCode', 'Race', 'Ethnicity', 'UTILITIES_PROCEED',
       'PAYROLL_PROCEED', 'MORTGAGE_INTEREST_PROCEED', 'RENT_PROCEED',
       'REFINANCE_EIDL_PROCEED', 'HEALTH_CARE_PROCEED',
       'DEBT_INTEREST_PROCEED', 'BusinessType', 'OriginatingLenderLocationID',
       'OriginatingLender', 'OriginatingLenderCity', 'OriginatingLenderState',
       'Gender', 'Veteran', 'NonProfit', 'ForgivenessAmount',
       'ForgivenessDate'],
      dtype='object')

In [5]:
df = df.drop(columns=["Unnamed: 0"])

In [6]:
# Rename column names with underscores
columns_dict = {"LoanNumber":"Loan_Number",
               "DateApproved":"Date_Approved",
               "SBAOfficeCode":"SBA_Office_Code",
               "ProcessingMethod":"Processing_Method",
               "BorrowerName":"Borrower_Name",
               "BorrowerAddress":"Borrower_Address",
               "BorrowerCity":"Borrower_City",
               "BorrowerState":"Borrower_State",
               "BorrowerZip":"Borrower_Zip",
               "LoanStatusDate":"Loan_Status_Date",
               "LoanStatus":"Loan_Status",
               "SBAGuarantyPercentage":"SBA_Guaranty_Percentage",
               "InitialApprovalAmount":"Initial_Approval_Amount",
               "CurrentApprovalAmount":"Current_Approval_Amount",
               "FranchiseName":"Franchise_Name",
               "ServicingLenderLocationID":"Servicing_Lender_Location_ID",
               "ServicingLenderName":"Servicing_Lender_Name",
               "ServicingLenderAddress":"Servicing_Lender_Address",
               "ServicingLenderCity":"Servicing_Lender_City",
               "ServicingLenderState":"Servicing_Lender_State",
               "ServicingLenderZip":"Servicing_Lender_Zip",
               "RuralUrbanIndicator":"Rural_Urban_Indicator",
               "HubzoneIndicator":"Hubzone_Indicator",
               "LMIIndicator":"LMI_Indicator",
               "BusinessAgeDescription":"Business_Age_Description",
               "ProjectCity":"Project_City",
               "ProjectCountyName":"Project_County_Name",
               "ProjectState":"Project_State",
               "ProjectZip":"Project_Zip",
               "NAICSCode":"NAICS_Code",
               "UTILITIES_PROCEED":"Utilities_Proceed",
               "PAYROLL_PROCEED":"Payroll_Proceed",
               "MORTGAGE_INTEREST_PROCEED":"Mortgage_Interest_Proceed",
               "RENT_PROCEED":"Rent_Proceed",
               "REFINANCE_EIDL_PROCEED":"Refinance_EIDL_Proceed",
               "HEALTH_CARE_PROCEED":"Health_Care_Proceed",
               "DEBT_INTEREST_PROCEED":"Debt_Interest_Proceed",
               "BusinessType":"Business_Type",
               "OriginatingLenderLocationID":"Originating_Lender_Location_ID",
               "OriginatingLender":"Originating_Lender",
               "OriginatingLenderCity":"Originating_Lender_City",
               "OriginatingLenderState":"Originating_Lender_State",
               "NonProfit":"Non_Profit",
               "ForgivenessAmount":"Forgiveness_Amount",
               "ForgivenessDate":"Forgiveness_Date"
              }
df = df.rename(columns=columns_dict)
df.columns

Index(['Loan_Number', 'Date_Approved', 'SBA_Office_Code', 'Processing_Method',
       'Borrower_Name', 'Borrower_Address', 'Borrower_City', 'Borrower_State',
       'Borrower_Zip', 'Loan_Status_Date', 'Loan_Status', 'Term',
       'SBA_Guaranty_Percentage', 'Initial_Approval_Amount',
       'Current_Approval_Amount', 'UndisbursedAmount', 'Franchise_Name',
       'Servicing_Lender_Location_ID', 'Servicing_Lender_Name',
       'Servicing_Lender_Address', 'Servicing_Lender_City',
       'Servicing_Lender_State', 'Servicing_Lender_Zip',
       'Rural_Urban_Indicator', 'Hubzone_Indicator', 'LMI_Indicator',
       'Business_Age_Description', 'Project_City', 'Project_County_Name',
       'Project_State', 'Project_Zip', 'CD', 'JobsReported', 'NAICS_Code',
       'Race', 'Ethnicity', 'Utilities_Proceed', 'Payroll_Proceed',
       'Mortgage_Interest_Proceed', 'Rent_Proceed', 'Refinance_EIDL_Proceed',
       'Health_Care_Proceed', 'Debt_Interest_Proceed', 'Business_Type',
       'Originating_Lender_Location_ID', 'Originating_Lender',
       'Originating_Lender_City', 'Originating_Lender_State', 'Gender',
       'Veteran', 'Non_Profit', 'Forgiveness_Amount', 'Forgiveness_Date'],
      dtype='object')

In [7]:
df.head()

,Loan_Number,Date_Approved,SBA_Office_Code,Processing_Method,Borrower_Name,Borrower_Address,Borrower_City,Borrower_State,Borrower_Zip,Loan_Status_Date,Loan_Status,Term,SBA_Guaranty_Percentage,Initial_Approval_Amount,Current_Approval_Amount,UndisbursedAmount,Franchise_Name,Servicing_Lender_Location_ID,Servicing_Lender_Name,Servicing_Lender_Address,Servicing_Lender_City,Servicing_Lender_State,Servicing_Lender_Zip,Rural_Urban_Indicator,Hubzone_Indicator,LMI_Indicator,Business_Age_Description,Project_City,Project_County_Name,Project_State,Project_Zip,CD,JobsReported,NAICS_Code,Race,Ethnicity,Utilities_Proceed,Payroll_Proceed,Mortgage_Interest_Proceed,Rent_Proceed,Refinance_EIDL_Proceed,Health_Care_Proceed,Debt_Interest_Proceed,Business_Type,Originating_Lender_Location_ID,Originating_Lender,Originating_Lender_City,Originating_Lender_State,Gender,Veteran,Non_Profit,Forgiveness_Amount,Forgiveness_Date
0,9547507704,05/01/2020,464.0,PPP,"SUMTER COATINGS, INC.",2410 Highway 15 South,Sumter,NaN,29150-9662,12/18/2020,Paid in Full,24,100,769358.78,769358.78,0.0,NaN,19248.0,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,N,N,Existing or more than 2 years old,Sumter,SUMTER,SC,29150-9662,SC-05,62.0,325510.0,Unanswered,Unknown/NotStated,NaN,769358.78,NaN,NaN,NaN,NaN,NaN,Corporation,19248.0,Synovus Bank,COLUMBUS,GA,Unanswered,Unanswered,NaN,773553.37,11/20/2020
1,9777677704,05/01/2020,464.0,PPP,"PLEASANT PLACES, INC.",7684 Southrail Road,North Charleston,NaN,29420-9000,09/28/2021,Paid in Full,24,100,736927.79,736927.79,0.0,NaN,19248.0,Synovus Bank,1148 Broadway,COLUMBUS,GA,31901-2429,U,Y,Y,Existing or more than 2 years old,North Charleston,CHARLESTON,SC,29420-9000,SC-06,73.0,561730.0,White,Unknown/NotStated,NaN,736927.79,NaN,NaN,NaN,NaN,NaN,Sole Proprietorship,19248.0,Synovus Bank,COLUMBUS,GA,Male Owned,Non-Veteran,NaN,746336.24,08/12/2021
2,5791407702,05/01/2020,1013.0,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,NaN,98112-2922,03/17/2021,Paid in Full,24,100,691355.00,691355.00,0.0,NaN,9551.0,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SEATTLE,KING,WA,98112-2922,WA-07,75.0,NaN,Unanswered,Unknown/NotStated,NaN,691355.00,NaN,NaN,NaN,NaN,NaN,Non-Profit Organization,9551.0,"Bank of America, National Association",CHARLOTTE,NC,Unanswered,Unanswered,Y,696677.49,02/10/2021
3,6223567700,05/01/2020,920.0,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,NaN,92407-1740,10/16/2021,Paid in Full,24,100,499871.00,499871.00,0.0,NaN,9551.0,"Bank of America, National Association","100 N Tryon St, Ste 170",CHARLOTTE,NC,28202-4024,U,N,N,New Business or 2 years or less,SAN BERNARDINO,SAN BERNARDINO,CA,92407-1740,CA-23,21.0,236115.0,American Indian or Alaska Native,Not Hispanic or Latino,NaN,499871.00,NaN,NaN,NaN,NaN,NaN,Corporation,9551.0,"Bank of America, National Association",CHARLOTTE,NC,Male Owned,Non-Veteran,NaN,395264.11,09/10/2021
4,9662437702,05/01/2020,101.0,PPP,AERO BOX LLC,NaN,NaN,NaN,NaN,08/17/2021,Paid in Full,24,100,367437.00,367437.00,0.0,NaN,57328.0,The Huntington National Bank,17 S High St.,COLUMBUS,OH,43215-3413,U,N,N,Unanswered,NaN,NaN,NaN,NaN,NaN,25.0,484210.0,Unanswered,Unknown/NotStated,NaN,367437.00,NaN,NaN,NaN,NaN,NaN,NaN,57328.0,The Huntington National Bank,COLUMBUS,OH,Unanswered,Unanswered,NaN,370819.35,04/08/2021

In [8]:
strings = list(df.dtypes[df.dtypes == 'object'].index)
strings

['Date_Approved',
 'Processing_Method',
 'Borrower_Name',
 'Borrower_Address',
 'Borrower_City',
 'Borrower_State',
 'Borrower_Zip',
 'Loan_Status_Date',
 'Loan_Status',
 'Franchise_Name',
 'Servicing_Lender_Name',
 'Servicing_Lender_Address',
 'Servicing_Lender_City',
 'Servicing_Lender_State',
 'Servicing_Lender_Zip',
 'Rural_Urban_Indicator',
 'Hubzone_Indicator',
 'LMI_Indicator',
 'Business_Age_Description',
 'Project_City',
 'Project_County_Name',
 'Project_State',
 'Project_Zip',
 'CD',
 'Race',
 'Ethnicity',
 'Business_Type',
 'Originating_Lender',
 'Originating_Lender_City',
 'Originating_Lender_State',
 'Gender',
 'Veteran',
 'Non_Profit',
 'Forgiveness_Date']

In [9]:
for col in strings:
    df[col] = df[col].str.upper()

In [10]:
df.head()

,Loan_Number,Date_Approved,SBA_Office_Code,Processing_Method,Borrower_Name,Borrower_Address,Borrower_City,Borrower_State,Borrower_Zip,Loan_Status_Date,Loan_Status,Term,SBA_Guaranty_Percentage,Initial_Approval_Amount,Current_Approval_Amount,UndisbursedAmount,Franchise_Name,Servicing_Lender_Location_ID,Servicing_Lender_Name,Servicing_Lender_Address,Servicing_Lender_City,Servicing_Lender_State,Servicing_Lender_Zip,Rural_Urban_Indicator,Hubzone_Indicator,LMI_Indicator,Business_Age_Description,Project_City,Project_County_Name,Project_State,Project_Zip,CD,JobsReported,NAICS_Code,Race,Ethnicity,Utilities_Proceed,Payroll_Proceed,Mortgage_Interest_Proceed,Rent_Proceed,Refinance_EIDL_Proceed,Health_Care_Proceed,Debt_Interest_Proceed,Business_Type,Originating_Lender_Location_ID,Originating_Lender,Originating_Lender_City,Originating_Lender_State,Gender,Veteran,Non_Profit,Forgiveness_Amount,Forgiveness_Date
0,9547507704,05/01/2020,464.0,PPP,"SUMTER COATINGS, INC.",2410 HIGHWAY 15 SOUTH,SUMTER,NaN,29150-9662,12/18/2020,PAID IN FULL,24,100,769358.78,769358.78,0.0,NaN,19248.0,SYNOVUS BANK,1148 BROADWAY,COLUMBUS,GA,31901-2429,U,N,N,EXISTING OR MORE THAN 2 YEARS OLD,SUMTER,SUMTER,SC,29150-9662,SC-05,62.0,325510.0,UNANSWERED,UNKNOWN/NOTSTATED,NaN,769358.78,NaN,NaN,NaN,NaN,NaN,CORPORATION,19248.0,SYNOVUS BANK,COLUMBUS,GA,UNANSWERED,UNANSWERED,NaN,773553.37,11/20/2020
1,9777677704,05/01/2020,464.0,PPP,"PLEASANT PLACES, INC.",7684 SOUTHRAIL ROAD,NORTH CHARLESTON,NaN,29420-9000,09/28/2021,PAID IN FULL,24,100,736927.79,736927.79,0.0,NaN,19248.0,SYNOVUS BANK,1148 BROADWAY,COLUMBUS,GA,31901-2429,U,Y,Y,EXISTING OR MORE THAN 2 YEARS OLD,NORTH CHARLESTON,CHARLESTON,SC,29420-9000,SC-06,73.0,561730.0,WHITE,UNKNOWN/NOTSTATED,NaN,736927.79,NaN,NaN,NaN,NaN,NaN,SOLE PROPRIETORSHIP,19248.0,SYNOVUS BANK,COLUMBUS,GA,MALE OWNED,NON-VETERAN,NaN,746336.24,08/12/2021
2,5791407702,05/01/2020,1013.0,PPP,BOYER CHILDREN'S CLINIC,1850 BOYER AVE E,SEATTLE,NaN,98112-2922,03/17/2021,PAID IN FULL,24,100,691355.00,691355.00,0.0,NaN,9551.0,"BANK OF AMERICA, NATIONAL ASSOCIATION","100 N TRYON ST, STE 170",CHARLOTTE,NC,28202-4024,U,N,N,NEW BUSINESS OR 2 YEARS OR LESS,SEATTLE,KING,WA,98112-2922,WA-07,75.0,NaN,UNANSWERED,UNKNOWN/NOTSTATED,NaN,691355.00,NaN,NaN,NaN,NaN,NaN,NON-PROFIT ORGANIZATION,9551.0,"BANK OF AMERICA, NATIONAL ASSOCIATION",CHARLOTTE,NC,UNANSWERED,UNANSWERED,Y,696677.49,02/10/2021
3,6223567700,05/01/2020,920.0,PPP,KIRTLEY CONSTRUCTION INC,1661 MARTIN RANCH RD,SAN BERNARDINO,NaN,92407-1740,10/16/2021,PAID IN FULL,24,100,499871.00,499871.00,0.0,NaN,9551.0,"BANK OF AMERICA, NATIONAL ASSOCIATION","100 N TRYON ST, STE 170",CHARLOTTE,NC,28202-4024,U,N,N,NEW BUSINESS OR 2 YEARS OR LESS,SAN BERNARDINO,SAN BERNARDINO,CA,92407-1740,CA-23,21.0,236115.0,AMERICAN INDIAN OR ALASKA NATIVE,NOT HISPANIC OR LATINO,NaN,499871.00,NaN,NaN,NaN,NaN,NaN,CORPORATION,9551.0,"BANK OF AMERICA, NATIONAL ASSOCIATION",CHARLOTTE,NC,MALE OWNED,NON-VETERAN,NaN,395264.11,09/10/2021
4,9662437702,05/01/2020,101.0,PPP,AERO BOX LLC,NaN,NaN,NaN,NaN,08/17/2021,PAID IN FULL,24,100,367437.00,367437.00,0.0,NaN,57328.0,THE HUNTINGTON NATIONAL BANK,17 S HIGH ST.,COLUMBUS,OH,43215-3413,U,N,N,UNANSWERED,NaN,NaN,NaN,NaN,NaN,25.0,484210.0,UNANSWERED,UNKNOWN/NOTSTATED,NaN,367437.00,NaN,NaN,NaN,NaN,NaN,NaN,57328.0,THE HUNTINGTON NATIONAL BANK,COLUMBUS,OH,UNANSWERED,UNANSWERED,NaN,370819.35,04/08/2021

In [11]:
df.isnull().sum()

Loan_Number                             0
Date_Approved                           0
SBA_Office_Code                        27
Processing_Method                       0
Borrower_Name                           5
Borrower_Address                      155
Borrower_City                         154
Borrower_State                        164
Borrower_Zip                          153
Loan_Status_Date                    59678
Loan_Status                             0
Term                                    0
SBA_Guaranty_Percentage                 0
Initial_Approval_Amount                 0
Current_Approval_Amount                 0
UndisbursedAmount                     110
Franchise_Name                    1815250
Servicing_Lender_Location_ID           27
Servicing_Lender_Name                  27
Servicing_Lender_Address               27
Servicing_Lender_City                  27
Servicing_Lender_State                 27
Servicing_Lender_Zip                   27
Rural_Urban_Indicator                   0
Hubzone_Indicator                       0
LMI_Indicator                           1
Business_Age_Description                1
Project_City                          156
Project_County_Name                   272
Project_State                         140
Project_Zip                           155
CD                                    246
JobsReported                            2
NAICS_Code                          20000
Race                                    0
Ethnicity                               0
Utilities_Proceed                 1255011
Payroll_Proceed                      2758
Mortgage_Interest_Proceed         1800185
Rent_Proceed                      1716282
Refinance_EIDL_Proceed            1833505
Health_Care_Proceed               1788360
Debt_Interest_Proceed             1821680
Business_Type                         871
Originating_Lender_Location_ID         27
Originating_Lender                     27
Originating_Lender_City                27
Originating_Lender_State               27
Gender                                  0
Veteran                                 0
Non_Profit                        1785494
Forgiveness_Amount                  90808
Forgiveness_Date                    90808
dtype: int64

In [12]:
# Fill any remaining nulls with "Not Available" - only for string columns
for col in strings:
    df[col] = df[col].fillna('Not Available')

In [13]:
df.to_csv('../data/cleaned/PPP_data/PPP_data.csv', encoding="utf-8")